"""Compile the DNA into the instruction files each AI tool reads on its own.

The MCP server is the primary, token-optimal delivery path — but two gaps remain:
not every developer drives an MCP-aware client, and even MCP clients only consult
the DNA when explicitly told to. So we also *compile* ``git_comment_memory.md`` into
the per-tool instruction files (CLAUDE.md, AGENTS.md, Cursor rules, Copilot
instructions). Each gets a standing instruction to call ``get_relevant_rules``
before writing code, plus a compact rule digest so the conventions apply even with
no MCP server at all.

To stay safe to re-run, shared files (CLAUDE.md / AGENTS.md / copilot-instructions)
are edited as **managed blocks** delimited by BEGIN/END markers — only the text
between the markers is rewritten, so a human's own notes are preserved. Dedicated
files we fully own (the Cursor ``.mdc``) are written wholesale.

This module performs no network or model calls; it is a pure ``Rule`` -> text
transform plus file upserts.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .memory import Rule

# Markers delimiting the generated region inside human-owned files. Kept as HTML
# comments so they render invisibly in Markdown and survive manual edits around them.
BEGIN = "<!-- BEGIN TEAM-CODING-DNA (generated by `dna compile`; edits inside are overwritten) -->"
END = "<!-- END TEAM-CODING-DNA -->"


@dataclass(frozen=True)
class Target:
    """One AI tool's instruction file.

    ``whole_file`` targets are owned entirely by us (written wholesale, optionally
    behind a ``header`` preamble such as Cursor's YAML frontmatter). Otherwise we
    upsert a managed block into whatever the file already contains.
    """

    key: str
    path: str
    whole_file: bool = False
    header: str = ""


# Cursor rules use a `.mdc` file with YAML frontmatter; `alwaysApply: true` makes
# the rule part of every request's context without the developer attaching it.
_CURSOR_HEADER = (
    "---\n"
    "description: Team Coding DNA — the team's mined PR-review conventions\n"
    "alwaysApply: true\n"
    "---\n\n"
)

TARGETS: tuple[Target, ...] = (
    Target("claude", "CLAUDE.md"),
    Target("agents", "AGENTS.md"),
    Target("copilot", ".github/copilot-instructions.md"),
    Target("cursor", ".cursor/rules/team-coding-dna.mdc", whole_file=True, header=_CURSOR_HEADER),
)

_TARGETS_BY_KEY = {t.key: t for t in TARGETS}


def resolve_targets(spec: str) -> list[str]:
    """Turn a ``--targets`` spec (``"all"`` or ``"claude,cursor"``) into known keys.

    Unknown keys raise ``ValueError`` so a typo fails loudly rather than silently
    writing nothing.
    """
    spec = (spec or "").strip().lower()
    if spec in ("", "all"):
        return [t.key for t in TARGETS]
    requested = [k.strip() for k in spec.split(",") if k.strip()]
    unknown = [k for k in requested if k not in _TARGETS_BY_KEY]
    if unknown:
        valid = ", ".join(_TARGETS_BY_KEY)
        raise ValueError(f"Unknown target(s): {', '.join(unknown)}. Valid: {valid}, all.")
    # De-duplicate while preserving the canonical TARGETS order.
    return [t.key for t in TARGETS if t.key in set(requested)]


def _scope(rule: Rule) -> str:
    """Compact human-readable scope, e.g. ``"python; billing/**, payments/**"``."""
    parts: list[str] = []
    if rule.languages:
        parts.append(", ".join(rule.languages))
    if rule.path_globs:
        parts.append(", ".join(rule.path_globs))
    return "; ".join(parts) if parts else "any"


def _digest_line(rule: Rule) -> str:
    rule_text = rule.rationale or rule.title
    return f"- `{rule.id}` ({rule.confidence:.2f}, {rule.category}; {_scope(rule)}): {rule_text}"


def render_block(rules: list[Rule]) -> str:
    """Render the shared instruction + rule digest used by every target.

    Rules are ordered by confidence (descending) so the strongest conventions lead,
    with numeric id as a stable tie-breaker.
    """
    ordered = sorted(rules, key=lambda r: (-r.confidence, r.numeric_id()))
    lines = [
        "# Team Coding DNA — the team's PR-review conventions",
        "",
        "These are conventions mined from this team's pull-request review history.",
        "**Before writing or changing code, consult them.**",
        "",
        "- If the `team-coding-dna` MCP server is available, call its `get_relevant_rules`",
        "  tool with your diff (or the files you're about to touch) for the scoped, ranked",
        "  rules, and `get_rule_detail` for the full rationale and precedent of one rule.",
        "- Otherwise, apply the digest below. Canonical source: `git_comment_memory.md`.",
        "",
        f"Rules ({len(ordered)}), as `id` (confidence, category; scope): rule —",
        "",
    ]
    lines.extend(_digest_line(r) for r in ordered)
    return "\n".join(lines)


def upsert_managed_block(existing_text: str, block_body: str) -> str:
    """Insert or replace the managed block in ``existing_text``.

    Idempotent: applying it twice yields the same result. Content outside the
    markers is preserved verbatim. If no markers exist yet, the block is appended.
    """
    block = f"{BEGIN}\n{block_body}\n{END}"
    if BEGIN in existing_text and END in existing_text:
        start = existing_text.index(BEGIN)
        end = existing_text.index(END) + len(END)
        return existing_text[:start] + block + existing_text[end:]
    trimmed = existing_text.rstrip()
    if trimmed:
        return f"{trimmed}\n\n{block}\n"
    return f"{block}\n"


def compile_targets(
    rules: list[Rule], keys: list[str], root: str | Path = "."
) -> list[tuple[str, str]]:
    """Write the instruction files for ``keys``; return ``[(key, path), ...]``.

    Parent directories (``.cursor/rules``, ``.github``) are created as needed.
    """
    root = Path(root)
    body = render_block(rules)
    written: list[tuple[str, str]] = []
    for key in keys:
        target = _TARGETS_BY_KEY[key]
        path = root / target.path
        if target.whole_file:
            content = f"{target.header}{body}\n"
        else:
            existing = path.read_text(encoding="utf-8") if path.exists() else ""
            content = upsert_managed_block(existing, body)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append((key, str(path)))
    return written


# --- CI: scheduled re-mining --------------------------------------------------

_CRON_BY_CADENCE = {
    "daily": "0 6 * * *",      # 06:00 UTC every day
    "weekly": "0 6 * * 1",     # 06:00 UTC every Monday
    "monthly": "0 6 1 * *",    # 06:00 UTC on the 1st
}


def ci_workflow_yaml(cadence: str = "daily", *, since: str = "30d") -> str:
    """Render a GitHub Actions workflow that re-mines on a schedule and opens a PR.

    The workflow runs ``mine -> distill -> compile`` and opens a pull request when
    the DNA (or any compiled instruction file) changes, so a human reviews new
    conventions before they land. Uses the built-in ``GITHUB_TOKEN`` by default;
    a PAT is only needed to mine a *different* repo or to let the PR trigger CI.
    """
    cadence = (cadence or "daily").strip().lower()
    if cadence not in _CRON_BY_CADENCE:
        valid = ", ".join(_CRON_BY_CADENCE)
        raise ValueError(f"Unknown cadence: {cadence}. Valid: {valid}.")
    cron = _CRON_BY_CADENCE[cadence]
    return f"""\
# Team Coding DNA — scheduled re-mine of PR-review conventions.
# Generated by `dna install-ci`. Re-mines history, re-distills the DNA, recompiles
# the per-tool instruction files, and opens a PR when anything changed.
name: Team Coding DNA

on:
  schedule:
    - cron: "{cron}"   # {cadence}, 06:00 UTC
  workflow_dispatch: {{}}   # allow manual runs from the Actions tab

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: team-coding-dna
  cancel-in-progress: false

jobs:
  remine:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Team Coding DNA
        # Once published to PyPI:
        run: pip install team-coding-dna
        # Until then, install from source instead (replace with your repo URL):
        # run: pip install "git+https://github.com/your-org/pr-review-comment-memory.git"

      - name: Re-mine, distill, and compile the DNA
        env:
          # Built-in token can read this repo's PRs. To mine a DIFFERENT repo, or to
          # let the resulting PR trigger CI, set a read-only PAT secret and use it here.
          GITHUB_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}
        run: |
          dna mine --since {since}
          dna distill
          dna compile

      - name: Open a PR if the DNA changed
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{{{ secrets.GITHUB_TOKEN }}}}
          branch: dna/auto-remine
          title: "chore(dna): scheduled re-mine of team review conventions"
          commit-message: "chore(dna): scheduled re-mine of team review conventions"
          body: |
            Automated re-mine of this repo's PR-review history by Team Coding DNA.

            Review the rule changes in `git_comment_memory.md` and the regenerated
            tool instruction files before merging. No changes => no PR is opened.
          labels: team-coding-dna
          add-paths: |
            git_comment_memory.md
            CLAUDE.md
            AGENTS.md
            .github/copilot-instructions.md
            .cursor/rules/team-coding-dna.mdc
"""
